### ISSUE TITLE
Autocompletion is not displayed correctly

### ISSUE THREAD

**Issue by FForthmann** [Darkgaja/Docdown#8]
When using the autocomplete function or the suggestion function for source information / citation, it is not correctly displayed as shown in the screenshot. This also applies to all other auto completions, e.g. when entering `\...` .

I don't know exactly why. I have added some headings but nothing else with the document.

![grafik](https://user-images.githubusercontent.com/52296146/69547052-2eec4000-0f95-11ea-9725-5647744bd8a3.png)

**Comment by Darkgaja** [comment]
I added some more error handling in the parsing and autocompletion methods in the latest update.

Does this issue still persist with 0.3.0.1?

**Comment by FForthmann** [comment]
Yes, the issue still persist with the newest version at this time `0.3.0.1`.

**Comment by Darkgaja** [comment]
Could you send me your workspace as a zip file in order to debug it?

Either via mail or as an attachment in a comment.

**Comment by FForthmann** [comment]
> 
> 
> Could you send me your workspace as a zip file in order to debug it?
> 
> Either via mail or as an attachment in a comment.

I sent you the workspace by mail :)

**Comment by Darkgaja** [comment]
Ok, so autocompletion for bibliographies only shows up when the bib file(s) can be parsed successfully. Yours currently contains a lot of invalid characters. You can see this by yourself when editing the bib file in docdown.

Generally, comments in bib/latex start with a `%` and need to be succeeded by an empty line. It should look like this:

```latex
@book{...}

% Some comment

@inproceedings{...}
```

If the issue persists, feel free to comment again. Otherwise please close the issue.

**Comment by FForthmann** [comment]
That solved it thank you very much! That concludes the issue. 

However, it might be worth considering throwing an `error` if the bib file is not read correctly.
